# Generated by Django 3.0.8 on 2020-08-28 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=200)),
                ('delivery', models.CharField(default='', max_length=200)),
                ('payment', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=70)),
                ('index_code', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cart.Cart')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='cart.Orders')),
            ],
        ),
    ]
