# Generated by Django 3.0.8 on 2020-08-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20200828_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imgurl',
            field=models.CharField(default='', max_length=300),
        ),
    ]
