# Generated by Django 3.0.8 on 2020-08-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_item_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.CharField(default='', max_length=400),
        ),
    ]
