# Generated by Django 3.0.8 on 2020-09-15 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20200915_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='promo',
        ),
        migrations.AddField(
            model_name='cart',
            name='promo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cart.Promocode'),
        ),
    ]
