# Generated by Django 3.1.3 on 2020-12-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_auto_20200925_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sale_price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
