# Generated by Django 3.1.3 on 2020-12-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_item_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='obiem',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='series',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
