# Generated by Django 3.0.8 on 2020-08-23 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=2000)),
                ('imgurl', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hairtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=2000)),
                ('imgurl', models.CharField(default='', max_length=1000)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('price', models.IntegerField()),
                ('description', models.CharField(default='', max_length=2000)),
                ('obiem', models.CharField(default='', max_length=10)),
                ('imgurl', models.CharField(default='', max_length=2000)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Category')),
                ('destination', models.ManyToManyField(to='products.Destination')),
                ('hairtype', models.ManyToManyField(to='products.Hairtype')),
                ('prtype', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Prtype')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Series')),
            ],
        ),
    ]
