# Generated by Django 3.0.8 on 2020-08-23 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='pr_brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='pr_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='destination',
            new_name='pr_destination',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='hairtype',
            new_name='pr_hairtype',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prtype',
            new_name='pr_prtype',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='series',
            new_name='pr_series',
        ),
    ]
