# Generated by Django 3.0.8 on 2020-08-23 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200823_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='brand',
            new_name='ser_brand',
        ),
    ]
