# Generated by Django 3.0.8 on 2020-08-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200823_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pr_category',
        ),
        migrations.AddField(
            model_name='product',
            name='pr_category',
            field=models.ManyToManyField(to='products.Category'),
        ),
    ]
