# Generated by Django 3.0.8 on 2020-08-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200825_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pr_prtype',
        ),
        migrations.AddField(
            model_name='product',
            name='pr_prtype',
            field=models.ManyToManyField(to='products.Prtype'),
        ),
    ]
