# Generated by Django 3.0.8 on 2020-09-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200907_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pr_series',
        ),
        migrations.AddField(
            model_name='product',
            name='pr_series',
            field=models.ManyToManyField(to='products.Series'),
        ),
    ]
