# Generated by Django 3.0.8 on 2020-09-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_product_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='imgurl',
            field=models.ImageField(upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='imgurl',
            field=models.ImageField(upload_to='static/images/products'),
        ),
    ]
