# Generated by Django 3.0.8 on 2020-09-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200925_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='imgurl',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='imgurl',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/products'),
        ),
    ]
