# Generated by Django 3.1.3 on 2020-12-08 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pr_status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='products.status'),
            preserve_default=False,
        ),
    ]
