# Generated by Django 3.1.3 on 2020-12-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20201210_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
